version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: FantasyRPG
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/databaserpg
      SPRING_DATASOURCE_USERNAME: Vik40
      SPRING_DATASOURCE_PASSWORD: PegvamTinko
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Shtepegnaviktor1!
      MYSQL_DATABASE: databaserpg
      MYSQL_USER: Vik40
      MYSQL_PASSWORD: PegvamTinko
    ports:
      - "3306:3306"
